import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'overview',
    'quickstart',
    {
      type: 'category',
      label: 'Skills',
      items: [{type: 'autogenerated', dirName: 'skills'}],
    },
    {
      type: 'category',
      label: 'Sample Projects',
      items: [{type: 'autogenerated', dirName: 'sample-projects'}],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
    'station',
  ],
};

export default sidebars;
