import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'quickstart',
    'api',
    'openai',
    'streaming',
    'batch',
    'reasoning',
    'rate-limits',
    'running-locally',
    'transcription',
    {
      type: 'category',
      label: 'Skills',
      items: [{ type: 'autogenerated', dirName: 'skills' }],
    },
    {
      type: 'category',
      label: 'Finetuning (beta)',
      items: [{ type: 'autogenerated', dirName: 'finetuning' }],
    },
    {
      type: 'category',
      label: 'Sample Projects',
      items: [{ type: 'autogenerated', dirName: 'sample-projects' }],
    },
    'faq',
    'pricing',
  ],
};

export default sidebars;
